const DB='3dvr-offline-library',VER=1,PROJECTS='projects',ASSETS='assets'
const req=(r)=>new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})
const done=(t)=>new Promise((a,b)=>{t.oncomplete=a;t.onerror=()=>b(t.error);t.onabort=()=>b(t.error)})
function open(){return new Promise((a,b)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(PROJECTS))db.createObjectStore(PROJECTS,{keyPath:'id'});if(!db.objectStoreNames.contains(ASSETS)){const s=db.createObjectStore(ASSETS,{keyPath:'key'});s.createIndex('projectId','projectId');s.createIndex('url','url')}};r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)})}
async function put(db,store,value){const t=db.transaction(store,'readwrite');t.objectStore(store).put(value);await done(t)}
async function clearAssets(db,projectId,keep=null){const t=db.transaction(ASSETS,'readwrite');const r=t.objectStore(ASSETS).index('projectId').openCursor(IDBKeyRange.only(projectId));r.onsuccess=()=>{const c=r.result;if(!c)return;if(!keep||c.value.revision!==keep)c.delete();c.continue()};await done(t)}
async function deleteRevision(db,projectId,revision){const t=db.transaction(ASSETS,'readwrite');const r=t.objectStore(ASSETS).index('projectId').openCursor(IDBKeyRange.only(projectId));r.onsuccess=()=>{const c=r.result;if(!c)return;if(c.value.revision===revision)c.delete();c.continue()};await done(t)}
async function hash(blob){if(!crypto.subtle)return null;const d=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function expand(values){const map=new Map();const add=(value,base=location.origin)=>{const d=typeof value==='string'?{url:value}:value;if(!d?.url)return;const u=new URL(d.url,base).href;map.set(u,{...map.get(u),...d,url:u})};(values||[]).forEach((x)=>add(x));for(const d of [...map.values()]){const u=new URL(d.url);if(!u.pathname.endsWith('/manifest.json'))continue;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`Manifest download ${r.status}`);const m=await r.json();if(m.kind!=='multires-cubemap'||!m.assetIndexUrl)continue;const iu=new URL(m.assetIndexUrl,u).href;add(iu);const ir=await fetch(iu,{cache:'no-store'});if(!ir.ok)throw new Error(`Asset index ${ir.status}`);const idx=await ir.json();for(const f of idx.files||[])add(f,iu)}return [...map.values()]}
export async function getDownloadedProject(id){const db=await open();try{const t=db.transaction(PROJECTS,'readonly');return (await req(t.objectStore(PROJECTS).get(id)))?.manifest||null}finally{db.close()}}
export async function getDownloadedProjectRecord(id){const db=await open();try{const t=db.transaction(PROJECTS,'readonly');return await req(t.objectStore(PROJECTS).get(id))}finally{db.close()}}
export async function getStorageEstimate(){try{return await navigator.storage?.estimate?.()}catch{return null}}
export async function downloadProject(manifest,onProgress=()=>{}){try{await navigator.storage?.persist?.()}catch{}const db=await open();const projectId=manifest.id,revision=manifest.revision;const assets=await expand(manifest.assets);let bytes=0;try{for(let i=0;i<assets.length;i++){const d=assets[i];const r=await fetch(d.url,{cache:'no-store'});if(!r.ok)throw new Error(`Download failed ${r.status}: ${d.url}`);const blob=await r.blob();if(d.bytes!=null&&Number(d.bytes)!==blob.size)throw new Error(`Size verification failed: ${d.url}`);if(d.sha256){const actual=await hash(blob);if(actual&&actual!==d.sha256)throw new Error(`SHA-256 verification failed: ${d.url}`)}bytes+=blob.size;await put(db,ASSETS,{key:`${projectId}::${revision}::${d.url}`,projectId,revision,url:d.url,blob,size:blob.size,type:blob.type,downloadedAt:Date.now()});onProgress({completed:i+1,total:assets.length,bytes,current:d.url})}await put(db,PROJECTS,{id:projectId,revision,manifest,downloadedAt:Date.now(),assetCount:assets.length,bytes});await clearAssets(db,projectId,revision);return{assetCount:assets.length,bytes}}catch(e){await deleteRevision(db,projectId,revision).catch(()=>{});throw e}finally{db.close()}}
export async function removeDownloadedProject(id){const db=await open();try{const t=db.transaction(PROJECTS,'readwrite');t.objectStore(PROJECTS).delete(id);await done(t);await clearAssets(db,id)}finally{db.close()}}
