import React, { useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { useFrame, useThree } from '@react-three/fiber'
import { panoramaTextureCache } from '../panorama/TextureLRU'
import { fillTileUrl, tileDirection, tileTransform } from '../panorama/cubemapGeometry'
import { usePanoramaManifest } from '../panorama/usePanoramaManifest'

function chooseLevel(manifest,camera,size) { const vf=THREE.MathUtils.degToRad(camera.fov||75); const hf=2*Math.atan(Math.tan(vf/2)*Math.max(1,size.width/Math.max(1,size.height))); const desired=size.width/Math.max(.01,hf)*(Math.PI/2); let best=manifest.levels[0]; for(const l of manifest.levels){best=l;if(l.faceSize>=desired*1.15)break} return best }
function allTiles(manifest,level){const out=[];for(const f of manifest.faces.map(x=>x.id))for(let row=0;row<level.tilesPerEdge;row++)for(let col=0;col<level.tilesPerEdge;col++)out.push({face:f,row,col,level});return out}
function visible(manifest,level,camera,size){const d=new THREE.Vector3();camera.getWorldDirection(d);const vf=THREE.MathUtils.degToRad(camera.fov||75);const hf=2*Math.atan(Math.tan(vf/2)*Math.max(1,size.width/Math.max(1,size.height)));const diagonal=Math.sqrt(vf*vf+hf*hf)/2+THREE.MathUtils.degToRad(22);const out=[];for(const f of manifest.faces.map(x=>x.id))for(let row=0;row<level.tilesPerEdge;row++)for(let col=0;col<level.tilesPerEdge;col++){const td=tileDirection(f,col,row,level.tilesPerEdge);const margin=(Math.PI/2)/level.tilesPerEdge; if(d.dot(td)>=Math.cos(Math.min(Math.PI,diagonal+margin)))out.push({face:f,row,col,level})}return out}
const key=(t)=>`${t.level.id}:${t.face}:${t.row}:${t.col}`

function Tile({tile,radius,opacity,order}) { const [texture,setTexture]=useState(null); const url=useMemo(()=>fillTileUrl(tile.level.tileUrlTemplate,{face:tile.face,level:tile.level.id,row:tile.row,col:tile.col}),[tile]); const tr=useMemo(()=>tileTransform(tile.face,tile.col,tile.row,tile.level.tilesPerEdge,radius,order?.03:.01),[tile,radius,order]); useEffect(()=>{let active=true;panoramaTextureCache.acquire(url).then(t=>active&&setTexture(t)).catch(()=>{});return()=>{active=false;setTexture(null);panoramaTextureCache.release(url)}},[url]); if(!texture)return null; return <mesh position={tr.position} quaternion={tr.quaternion} scale={tr.scale} renderOrder={order} frustumCulled={false}><planeGeometry args={[1,1]}/><meshBasicMaterial map={texture} side={THREE.DoubleSide} transparent={opacity<1} opacity={opacity} depthWrite={false} toneMapped={false}/></mesh> }

export default function MultiResPanorama({manifestUrl,opacity=1,radius=50,gpuBudgetBytes=192*1024*1024}) { const {manifest,error}=usePanoramaManifest(manifestUrl); const {camera,size}=useThree(); const [detail,setDetail]=useState([]); const sig=useRef(''); const last=useRef(0); useEffect(()=>panoramaTextureCache.setBudget(gpuBudgetBytes),[gpuBudgetBytes]); const base=useMemo(()=>manifest?allTiles(manifest,manifest.levels.find(x=>x.id===manifest.baseLevel)||manifest.levels[0]):[],[manifest]); useFrame(({clock})=>{if(!manifest)return;const ms=clock.elapsedTime*1000;if(ms-last.current<180)return;last.current=ms;const level=chooseLevel(manifest,camera,size);if(level.id===manifest.baseLevel){if(sig.current){sig.current='';setDetail([])}return}const next=visible(manifest,level,camera,size);const s=next.map(key).sort().join('|');if(s!==sig.current){sig.current=s;setDetail(next)}}); if(error){console.warn(error);return null} if(!manifest)return null; return <group>{base.map(t=><Tile key={`b:${key(t)}`} tile={t} radius={radius} opacity={opacity} order={0}/>)}{detail.map(t=><Tile key={`d:${key(t)}`} tile={t} radius={radius} opacity={opacity} order={1}/>)}</group> }
